package modelo;
// Generated 13-dic-2018 16:06:53 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Archivo generated by hbm2java
 */
public class Archivo  implements java.io.Serializable {


     private Integer idArchivo;
     private Proyecto proyecto;
     private String nombre;
     private Set versions = new HashSet(0);

    public Archivo() {
    }

	
    public Archivo(Proyecto proyecto, String nombre) {
        this.proyecto = proyecto;
        this.nombre = nombre;
    }
    public Archivo(Proyecto proyecto, String nombre, Set versions) {
       this.proyecto = proyecto;
       this.nombre = nombre;
       this.versions = versions;
    }
   
    public Integer getIdArchivo() {
        return this.idArchivo;
    }
    
    public void setIdArchivo(Integer idArchivo) {
        this.idArchivo = idArchivo;
    }
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getVersions() {
        return this.versions;
    }
    
    public void setVersions(Set versions) {
        this.versions = versions;
    }




}


