package modelo;
// Generated 13-dic-2018 16:06:53 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Chatgrupo generated by hbm2java
 */
public class Chatgrupo  implements java.io.Serializable {


     private Integer idChatGrupo;
     private String nombre;
     private Set mensajes = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Chatgrupo() {
    }

	
    public Chatgrupo(String nombre) {
        this.nombre = nombre;
    }
    public Chatgrupo(String nombre, Set mensajes, Set usuarios) {
       this.nombre = nombre;
       this.mensajes = mensajes;
       this.usuarios = usuarios;
    }
   
    public Integer getIdChatGrupo() {
        return this.idChatGrupo;
    }
    
    public void setIdChatGrupo(Integer idChatGrupo) {
        this.idChatGrupo = idChatGrupo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getMensajes() {
        return this.mensajes;
    }
    
    public void setMensajes(Set mensajes) {
        this.mensajes = mensajes;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


