package modelo;
// Generated 13-dic-2018 16:06:53 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto  implements java.io.Serializable {


     private Integer idProyecto;
     private Cliente cliente;
     private String nombre;
     private Date fip;
     private Date ffp;
     private Date fir;
     private Date ffr;
     private boolean estado;
     private Set requisitos = new HashSet(0);
     private Set archivos = new HashSet(0);
     private Set rolUsuarioProyectos = new HashSet(0);

    public Proyecto() {
    }

	
    public Proyecto(Cliente cliente, String nombre, boolean estado) {
        this.cliente = cliente;
        this.nombre = nombre;
        this.estado = estado;
    }
    public Proyecto(Cliente cliente, String nombre, Date fip, Date ffp, Date fir, Date ffr, boolean estado, Set requisitos, Set archivos, Set rolUsuarioProyectos) {
       this.cliente = cliente;
       this.nombre = nombre;
       this.fip = fip;
       this.ffp = ffp;
       this.fir = fir;
       this.ffr = ffr;
       this.estado = estado;
       this.requisitos = requisitos;
       this.archivos = archivos;
       this.rolUsuarioProyectos = rolUsuarioProyectos;
    }
   
    public Integer getIdProyecto() {
        return this.idProyecto;
    }
    
    public void setIdProyecto(Integer idProyecto) {
        this.idProyecto = idProyecto;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFip() {
        return this.fip;
    }
    
    public void setFip(Date fip) {
        this.fip = fip;
    }
    public Date getFfp() {
        return this.ffp;
    }
    
    public void setFfp(Date ffp) {
        this.ffp = ffp;
    }
    public Date getFir() {
        return this.fir;
    }
    
    public void setFir(Date fir) {
        this.fir = fir;
    }
    public Date getFfr() {
        return this.ffr;
    }
    
    public void setFfr(Date ffr) {
        this.ffr = ffr;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set getRequisitos() {
        return this.requisitos;
    }
    
    public void setRequisitos(Set requisitos) {
        this.requisitos = requisitos;
    }
    public Set getArchivos() {
        return this.archivos;
    }
    
    public void setArchivos(Set archivos) {
        this.archivos = archivos;
    }
    public Set getRolUsuarioProyectos() {
        return this.rolUsuarioProyectos;
    }
    
    public void setRolUsuarioProyectos(Set rolUsuarioProyectos) {
        this.rolUsuarioProyectos = rolUsuarioProyectos;
    }




}


