package modelo;
// Generated 13-dic-2018 16:06:53 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Requisito generated by hbm2java
 */
public class Requisito  implements java.io.Serializable {


     private Integer idRequisito;
     private Prioridad prioridad;
     private Proyecto proyecto;
     private Usuario usuario;
     private Date fecha;
     private boolean esIncidencia;
     private boolean finalizado;
     private String ruta;
     private Set tareas = new HashSet(0);

    public Requisito() {
    }

	
    public Requisito(Prioridad prioridad, Proyecto proyecto, Usuario usuario, Date fecha, boolean esIncidencia, boolean finalizado) {
        this.prioridad = prioridad;
        this.proyecto = proyecto;
        this.usuario = usuario;
        this.fecha = fecha;
        this.esIncidencia = esIncidencia;
        this.finalizado = finalizado;
    }
    public Requisito(Prioridad prioridad, Proyecto proyecto, Usuario usuario, Date fecha, boolean esIncidencia, boolean finalizado, String ruta, Set tareas) {
       this.prioridad = prioridad;
       this.proyecto = proyecto;
       this.usuario = usuario;
       this.fecha = fecha;
       this.esIncidencia = esIncidencia;
       this.finalizado = finalizado;
       this.ruta = ruta;
       this.tareas = tareas;
    }
   
    public Integer getIdRequisito() {
        return this.idRequisito;
    }
    
    public void setIdRequisito(Integer idRequisito) {
        this.idRequisito = idRequisito;
    }
    public Prioridad getPrioridad() {
        return this.prioridad;
    }
    
    public void setPrioridad(Prioridad prioridad) {
        this.prioridad = prioridad;
    }
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public boolean isEsIncidencia() {
        return this.esIncidencia;
    }
    
    public void setEsIncidencia(boolean esIncidencia) {
        this.esIncidencia = esIncidencia;
    }
    public boolean isFinalizado() {
        return this.finalizado;
    }
    
    public void setFinalizado(boolean finalizado) {
        this.finalizado = finalizado;
    }
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }
    public Set getTareas() {
        return this.tareas;
    }
    
    public void setTareas(Set tareas) {
        this.tareas = tareas;
    }




}


