package modelo;
// Generated 13-dic-2018 16:06:53 by Hibernate Tools 4.3.1



/**
 * RolUsuarioProyectoId generated by hbm2java
 */
public class RolUsuarioProyectoId  implements java.io.Serializable {


     private int idRol;
     private int idUsuario;
     private int idProyecto;

    public RolUsuarioProyectoId() {
    }

    public RolUsuarioProyectoId(int idRol, int idUsuario, int idProyecto) {
       this.idRol = idRol;
       this.idUsuario = idUsuario;
       this.idProyecto = idProyecto;
    }
   
    public int getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(int idRol) {
        this.idRol = idRol;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public int getIdProyecto() {
        return this.idProyecto;
    }
    
    public void setIdProyecto(int idProyecto) {
        this.idProyecto = idProyecto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RolUsuarioProyectoId) ) return false;
		 RolUsuarioProyectoId castOther = ( RolUsuarioProyectoId ) other; 
         
		 return (this.getIdRol()==castOther.getIdRol())
 && (this.getIdUsuario()==castOther.getIdUsuario())
 && (this.getIdProyecto()==castOther.getIdProyecto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdRol();
         result = 37 * result + this.getIdUsuario();
         result = 37 * result + this.getIdProyecto();
         return result;
   }   


}


