package modelo;
// Generated 13-dic-2018 16:06:53 by Hibernate Tools 4.3.1



/**
 * RolUsuarioProyecto generated by hbm2java
 */
public class RolUsuarioProyecto  implements java.io.Serializable {


     private RolUsuarioProyectoId id;
     private Proyecto proyecto;
     private Rol rol;
     private Usuario usuario;

    public RolUsuarioProyecto() {
    }

    public RolUsuarioProyecto(RolUsuarioProyectoId id, Proyecto proyecto, Rol rol, Usuario usuario) {
       this.id = id;
       this.proyecto = proyecto;
       this.rol = rol;
       this.usuario = usuario;
    }
   
    public RolUsuarioProyectoId getId() {
        return this.id;
    }
    
    public void setId(RolUsuarioProyectoId id) {
        this.id = id;
    }
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


