package modelo;
// Generated 13-dic-2018 16:06:53 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tarea generated by hbm2java
 */
public class Tarea  implements java.io.Serializable {


     private Integer idTarea;
     private Requisito requisito;
     private Tarea tarea;
     private String descripcion;
     private Date fip;
     private Date ffp;
     private Date fir;
     private Date ffr;
     private Set tareas = new HashSet(0);
     private Set informes = new HashSet(0);
     private Set alertas = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Tarea() {
    }

	
    public Tarea(Requisito requisito, String descripcion) {
        this.requisito = requisito;
        this.descripcion = descripcion;
    }
    public Tarea(Requisito requisito, Tarea tarea, String descripcion, Date fip, Date ffp, Date fir, Date ffr, Set tareas, Set informes, Set alertas, Set usuarios) {
       this.requisito = requisito;
       this.tarea = tarea;
       this.descripcion = descripcion;
       this.fip = fip;
       this.ffp = ffp;
       this.fir = fir;
       this.ffr = ffr;
       this.tareas = tareas;
       this.informes = informes;
       this.alertas = alertas;
       this.usuarios = usuarios;
    }
   
    public Integer getIdTarea() {
        return this.idTarea;
    }
    
    public void setIdTarea(Integer idTarea) {
        this.idTarea = idTarea;
    }
    public Requisito getRequisito() {
        return this.requisito;
    }
    
    public void setRequisito(Requisito requisito) {
        this.requisito = requisito;
    }
    public Tarea getTarea() {
        return this.tarea;
    }
    
    public void setTarea(Tarea tarea) {
        this.tarea = tarea;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFip() {
        return this.fip;
    }
    
    public void setFip(Date fip) {
        this.fip = fip;
    }
    public Date getFfp() {
        return this.ffp;
    }
    
    public void setFfp(Date ffp) {
        this.ffp = ffp;
    }
    public Date getFir() {
        return this.fir;
    }
    
    public void setFir(Date fir) {
        this.fir = fir;
    }
    public Date getFfr() {
        return this.ffr;
    }
    
    public void setFfr(Date ffr) {
        this.ffr = ffr;
    }
    public Set getTareas() {
        return this.tareas;
    }
    
    public void setTareas(Set tareas) {
        this.tareas = tareas;
    }
    public Set getInformes() {
        return this.informes;
    }
    
    public void setInformes(Set informes) {
        this.informes = informes;
    }
    public Set getAlertas() {
        return this.alertas;
    }
    
    public void setAlertas(Set alertas) {
        this.alertas = alertas;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


