package modelo;
// Generated 13-dic-2018 16:06:53 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * UsuarioAlerta generated by hbm2java
 */
public class UsuarioAlerta  implements java.io.Serializable {


     private UsuarioAlertaId id;
     private Alerta alerta;
     private Usuario usuario;
     private Date fechaVisto;

    public UsuarioAlerta() {
    }

	
    public UsuarioAlerta(UsuarioAlertaId id, Alerta alerta, Usuario usuario) {
        this.id = id;
        this.alerta = alerta;
        this.usuario = usuario;
    }
    public UsuarioAlerta(UsuarioAlertaId id, Alerta alerta, Usuario usuario, Date fechaVisto) {
       this.id = id;
       this.alerta = alerta;
       this.usuario = usuario;
       this.fechaVisto = fechaVisto;
    }
   
    public UsuarioAlertaId getId() {
        return this.id;
    }
    
    public void setId(UsuarioAlertaId id) {
        this.id = id;
    }
    public Alerta getAlerta() {
        return this.alerta;
    }
    
    public void setAlerta(Alerta alerta) {
        this.alerta = alerta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaVisto() {
        return this.fechaVisto;
    }
    
    public void setFechaVisto(Date fechaVisto) {
        this.fechaVisto = fechaVisto;
    }




}


