package modelo;
// Generated 13-dic-2018 16:06:53 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Version generated by hbm2java
 */
public class Version  implements java.io.Serializable {


     private Integer idVersion;
     private Archivo archivo;
     private Usuario usuario;
     private String nombre;
     private Date fecha;
     private String path;
     private Boolean esFinal;

    public Version() {
    }

	
    public Version(Archivo archivo, Usuario usuario, String nombre, Date fecha, String path) {
        this.archivo = archivo;
        this.usuario = usuario;
        this.nombre = nombre;
        this.fecha = fecha;
        this.path = path;
    }
    public Version(Archivo archivo, Usuario usuario, String nombre, Date fecha, String path, Boolean esFinal) {
       this.archivo = archivo;
       this.usuario = usuario;
       this.nombre = nombre;
       this.fecha = fecha;
       this.path = path;
       this.esFinal = esFinal;
    }
   
    public Integer getIdVersion() {
        return this.idVersion;
    }
    
    public void setIdVersion(Integer idVersion) {
        this.idVersion = idVersion;
    }
    public Archivo getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(Archivo archivo) {
        this.archivo = archivo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public Boolean getEsFinal() {
        return this.esFinal;
    }
    
    public void setEsFinal(Boolean esFinal) {
        this.esFinal = esFinal;
    }




}


